/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scindx;

import io.dropwizard.Application;
import io.dropwizard.setup.Environment;

public class ScindxApplication extends Application<ScindxConfiguration> {
    public static void main(String[] args) throws Exception {
        new ScindxApplication().run(args);
    }


    public void run(ScindxConfiguration configuration, Environment environment) {
    }
}
